[workspace]
authors = ["A. R. Shajii <ars@ars.me>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025102605,<0.26"
